### ISSUE TITLE
`ImageProcessor` integration and consolidation

### ISSUE THREAD

**Issue by gregbubnis** [focolab/image-processing#4]
I see huge overlap between `ImageProcessor` and segfunctions.py content, so it's high time to consolidate! To nudge this along, I suggest the following (some of which was already suggested by others) but am fully open to another plan

### Work items
- Move standalone functions from ImageProcessor.py to segfunctions.py
- Make `ImageProcessor` import from segfunctions
- Make other codebases (wb-live) import _this_ `ImageProcessor` and delete the others
- Make unit/integration tests to ensure nothing breaks during consolidation
- Consolidation phase 1 (non-breaking): Keep existing functions for backwards compatibility, but have them wrap new/refactored code.
- Consolidation phase 2 (possibly breaking changes)

### Big picture considerations (subjective, all open to pushback)
- `ImageProcessor` is doing exclusively 2D analysis and appears to have been tuned for speed, so any refactoring cannot hamper its performance.
- We should be crystal clear about what routines are 2D, 3D, ND, and hybrids. 
- Functions should not pretend to be 3D while tacitly treating Z (or Y or X) differently (i.e. processing a 3D volume by looping over 2D planes). It's better to handle this type of cleverness in calling code.
- If this library is to span multiple projects and microscope configs, (and it should) we should eliminate hard coded parameters and be skeptical of case-specific defaults. Maybe another directory could house project/microscope optimized parameter dicts.

**Comment by gregbubnis** [comment]
@RaymondDunn are you using this ImageProcessor class? If not we should just delete it from this codebase to avoid having it duplicated. To my knowledge, this copy is not in use anywhere else.

**Comment by RaymondDunn** [comment]
Thanks for checking on this! 
* I still use ImageProcessor for a few different convenience cases, and as part of a closed-loop algorithm that i no longer use. 
* as you point out it's a bundle of filtering and peakfinding, so i suppose the appropriate refactor would be splitting into `segfunctions.py` and `filtering.py`, then as you suggest, refactor apparatus-specific defaults into somewhere else. 
* correct this `image-processing` copy isn't used. there's another copy in the `wb-live` repo and the original plan was to deprecate that one in favor of the one here in `image-processor`. 

so based on this and #5 let's delete this version, as you suggest.

**Comment by RaymondDunn** [comment]
deleted file in pull request. thanks greg!
